#CFLAGS = -g -Wall -Wextra -pedantic -Wno-unused-parameter
CFLAGS = -g -Wno-unused-parameter
CC = gcc

PROGRAMS =   tests_ecosys ecosys

.PHONY:	all clean

all: $(PROGRAMS)

tests_ecosys: ecosys.o main_tests.o
	$(CC) -o $@ $(CFLAGS) $^


ecosys: ecosys.o main_ecosys.o
	$(CC) -o $@ $(CFLAGS) $^

ecosys.o: ecosys.c
	gcc $(CFLAGS) -c ecosys.c

main_tests.o: main_tests.c
	gcc $(CFLAGS) -c main_tests.c

main_ecosys.o: main_ecosys.c 
	gcc $(CFLAGS) -c main_ecosys.c

#Ou plus simplement
#%.o:%.c %.h
#	$(CC)  $(GCC_FLAGS) -c  $<


clean:
	rm -f *.o *~ $(PROGRAMS)

tests_ecosys2: main_test.o ecosys.o 
	gcc -o tests_ecosys2 main_test.o ecosys.o 

main_test.o: main_test.c ecosys.h
	gcc -c main_test.c 

mon_programme: main_test.c ecosys.c 
	gcc -Wall -o mon_programme main_test.c ecosys.c 
programme: main_test.c ecosys.c 
	gcc -Wall -o mon_programme main_test.c ecosys.c

main_test: main_ecosys.c ecosys.c 
	gcc -Wall -o main_test main_ecosys.c ecosys.c 
main_ecosys: main_ecosys.c ecosys.c 
	gcc -Wall -o main_ecosys main_ecosys.c ecosys.c  

test_ecosys: main_ecosys.c ecosys.c 
	gcc -Wall -o test_ecosys main_ecosys.c ecosys.c  

